# Generated by Django 5.1.2 on 2025-02-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_livro_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='status',
            field=models.CharField(choices=[('Lendo', 'Lendo'), ('Lido', 'Lido'), ('Deseja-se', 'Deseja-se')], max_length=9, verbose_name='Status'),
        ),
    ]
