# Generated by Django 5.1.2 on 2025-03-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_livro_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='status',
            field=models.CharField(choices=[('Lendo', 'Lendo'), ('Finalizado', 'Finalizado'), ('Deseja-se', 'Deseja-se')], max_length=12, verbose_name='Status'),
        ),
    ]
